name: Deploy Memory Game
# Trigger the workflow on pushes to the main branch.
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js and cache npm dependencies for faster builds
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      # Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Build the Vite app. This command will create a 'dist' folder.
      - name: Build App
        run: npm run build

      # Deploy the build to GitHub Pages using peaceiris action.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
